#ifndef conquest_types_h__
#define conquest_types_h__

typedef enum {
	CONQUEST_NODE_TYPE__TOP_LEFT_EDGE = 0,
	CONQUEST_NODE_TYPE__TOP_RIGHT_EDGE = 1,
	CONQUEST_NODE_TYPE__BOTTOM_LEFT_EDGE = 2,
	CONQUEST_NODE_TYPE__BOTTOM_RIGHT_EDGE = 3,
	CONQUEST_NODE_TYPE__TOP_T = 4,
	CONQUEST_NODE_TYPE__RIGHT_T = 5,
	CONQUEST_NODE_TYPE__BOTTOM_T = 6,
	CONQUEST_NODE_TYPE__LEFT_T = 7,
	CONQUEST_NODE_TYPE__CROSS = 8,
	CONQUEST_NODE_TYPE__UNKNOWN = 9
} conquest_ENodeType_t;

#endif // conquest_types_h__
