#ifndef hal_int_types_h__
#define hal_int_types_h__

#include "common.h"


typedef enum {
	HAL_INT_PRIORITY__0 = 0,
	HAL_INT_PRIORITY__1,
	HAL_INT_PRIORITY__2,
	HAL_INT_PRIORITY__3,
	HAL_INT_PRIORITY__4,
	HAL_INT_PRIORITY__5,
	HAL_INT_PRIORITY__6,
	HAL_INT_PRIORITY__7
} hal_int_EPriority_t;


typedef enum {
	HAL_INT_SOURCE__ADC_COMPLETE,
	HAL_INT_SOURCE__BROWNOUT,
	HAL_INT_SOURCE__CAN1,
	HAL_INT_SOURCE__CAN2,
	HAL_INT_SOURCE__DATA_CONVERTER,
	HAL_INT_SOURCE__EXTERNAL0,
	HAL_INT_SOURCE__EXTERNAL1,
	HAL_INT_SOURCE__EXTERNAL2,
	HAL_INT_SOURCE__EXTERNAL3,
	HAL_INT_SOURCE__EXTERNAL4,
	HAL_INT_SOURCE__I2C_BUS_COLLISION,
	HAL_INT_SOURCE__I2C_TRANSFER_COMPLETE,
	HAL_INT_SOURCE__INPUT_CAPTURE_CHAN1,
	HAL_INT_SOURCE__INPUT_CAPTURE_CHAN2,
	HAL_INT_SOURCE__INPUT_CAPTURE_CHAN3,
	HAL_INT_SOURCE__INPUT_CAPTURE_CHAN4,
	HAL_INT_SOURCE__INPUT_CAPTURE_CHAN5,
	HAL_INT_SOURCE__INPUT_CAPTURE_CHAN6,
	HAL_INT_SOURCE__INPUT_CAPTURE_CHAN7,
	HAL_INT_SOURCE__INPUT_CAPTURE_CHAN8,
	HAL_INT_SOURCE__INPUT_CHANGED,
	HAL_INT_SOURCE__MEMORY_WRITE_COMPLETE,
	HAL_INT_SOURCE__OUTPUT_COMPARE_CHAN1,
	HAL_INT_SOURCE__OUTPUT_COMPARE_CHAN2,
	HAL_INT_SOURCE__OUTPUT_COMPARE_CHAN3,
	HAL_INT_SOURCE__OUTPUT_COMPARE_CHAN4,
	HAL_INT_SOURCE__OUTPUT_COMPARE_CHAN5,
	HAL_INT_SOURCE__OUTPUT_COMPARE_CHAN6,
	HAL_INT_SOURCE__OUTPUT_COMPARE_CHAN7,
	HAL_INT_SOURCE__OUTPUT_COMPARE_CHAN8,
	HAL_INT_SOURCE__SPI1,
	HAL_INT_SOURCE__SPI2,
	HAL_INT_SOURCE__TIMER1,
	HAL_INT_SOURCE__TIMER2,
	HAL_INT_SOURCE__TIMER3,
	HAL_INT_SOURCE__TIMER4,
	HAL_INT_SOURCE__TIMER5,
	HAL_INT_SOURCE__UART1_RECEIVER,
	HAL_INT_SOURCE__UART1_TRANSMITTER,
	HAL_INT_SOURCE__UART2_RECEIVER,
	HAL_INT_SOURCE__UART2_TRANSMITTER
} hal_int_ESource_t;


#endif /* hal_int_types_h__ */
